[build]
  command = "npm run build"  # Adjust based on your project's build script
  publish = "client/build"   # Adjust based on your project's build output directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200